// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: als/als.proto

package als

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CreateAlarmRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID int64 `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
}

func (x *CreateAlarmRequest) Reset() {
	*x = CreateAlarmRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_als_als_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAlarmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAlarmRequest) ProtoMessage() {}

func (x *CreateAlarmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_als_als_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAlarmRequest.ProtoReflect.Descriptor instead.
func (*CreateAlarmRequest) Descriptor() ([]byte, []int) {
	return file_als_als_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAlarmRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

var File_als_als_proto protoreflect.FileDescriptor

var file_als_als_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x61, 0x6c, 0x73, 0x2f, 0x61, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x03, 0x61, 0x6c, 0x73, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x2c, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x6c, 0x61, 0x72, 0x6d,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x32,
	0x56, 0x0a, 0x12, 0x41, 0x6c, 0x61, 0x72, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x40, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41,
	0x6c, 0x61, 0x72, 0x6d, 0x12, 0x17, 0x2e, 0x61, 0x6c, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x41, 0x6c, 0x61, 0x72, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x42, 0x45, 0x0a, 0x15, 0x69, 0x6f, 0x2e, 0x63, 0x68,
	0x69, 0x72, 0x70, 0x73, 0x74, 0x61, 0x63, 0x6b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x6c, 0x73,
	0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x62, 0x72,
	0x61, 0x68, 0x69, 0x6d, 0x6f, 0x7a, 0x65, 0x6b, 0x69, 0x63, 0x69, 0x2f, 0x63, 0x68, 0x69, 0x72,
	0x70, 0x73, 0x74, 0x61, 0x63, 0x6b, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6c, 0x73, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_als_als_proto_rawDescOnce sync.Once
	file_als_als_proto_rawDescData = file_als_als_proto_rawDesc
)

func file_als_als_proto_rawDescGZIP() []byte {
	file_als_als_proto_rawDescOnce.Do(func() {
		file_als_als_proto_rawDescData = protoimpl.X.CompressGZIP(file_als_als_proto_rawDescData)
	})
	return file_als_als_proto_rawDescData
}

var file_als_als_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_als_als_proto_goTypes = []interface{}{
	(*CreateAlarmRequest)(nil), // 0: als.CreateAlarmRequest
	(*empty.Empty)(nil),        // 1: google.protobuf.Empty
}
var file_als_als_proto_depIdxs = []int32{
	0, // 0: als.AlarmServerService.CreateAlarm:input_type -> als.CreateAlarmRequest
	1, // 1: als.AlarmServerService.CreateAlarm:output_type -> google.protobuf.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_als_als_proto_init() }
func file_als_als_proto_init() {
	if File_als_als_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_als_als_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAlarmRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_als_als_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_als_als_proto_goTypes,
		DependencyIndexes: file_als_als_proto_depIdxs,
		MessageInfos:      file_als_als_proto_msgTypes,
	}.Build()
	File_als_als_proto = out.File
	file_als_als_proto_rawDesc = nil
	file_als_als_proto_goTypes = nil
	file_als_als_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AlarmServerServiceClient is the client API for AlarmServerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AlarmServerServiceClient interface {
	// CreateDevice creates the given device.
	CreateAlarm(ctx context.Context, in *CreateAlarmRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type alarmServerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAlarmServerServiceClient(cc grpc.ClientConnInterface) AlarmServerServiceClient {
	return &alarmServerServiceClient{cc}
}

func (c *alarmServerServiceClient) CreateAlarm(ctx context.Context, in *CreateAlarmRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/als.AlarmServerService/CreateAlarm", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AlarmServerServiceServer is the server API for AlarmServerService service.
type AlarmServerServiceServer interface {
	// CreateDevice creates the given device.
	CreateAlarm(context.Context, *CreateAlarmRequest) (*empty.Empty, error)
}

// UnimplementedAlarmServerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAlarmServerServiceServer struct {
}

func (*UnimplementedAlarmServerServiceServer) CreateAlarm(context.Context, *CreateAlarmRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAlarm not implemented")
}

func RegisterAlarmServerServiceServer(s *grpc.Server, srv AlarmServerServiceServer) {
	s.RegisterService(&_AlarmServerService_serviceDesc, srv)
}

func _AlarmServerService_CreateAlarm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAlarmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlarmServerServiceServer).CreateAlarm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/als.AlarmServerService/CreateAlarm",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlarmServerServiceServer).CreateAlarm(ctx, req.(*CreateAlarmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AlarmServerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "als.AlarmServerService",
	HandlerType: (*AlarmServerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAlarm",
			Handler:    _AlarmServerService_CreateAlarm_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "als/als.proto",
}
