// Code generated by protoc-gen-go. DO NOT EDIT.
// source: als/als.proto

package als

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/duration"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/ibrahimozekici/chirpstack-api/go/v3/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Alarm struct {
	// Alarm id.
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Device EUI (HEX encoded).
	DevEui string `protobuf:"bytes,2,opt,name=dev_eui,json=devEUI,proto3" json:"dev_eui,omitempty"`
	// Condition of alarm
	MinTreshold float32 `protobuf:"fixed32,3,opt,name=min_treshold,json=minTreshold,proto3" json:"min_treshold,omitempty"`
	// Value of alarm
	MaxTreshold          float32              `protobuf:"fixed32,4,opt,name=max_treshold,json=maxTreshold,proto3" json:"max_treshold,omitempty"`
	Sms                  bool                 `protobuf:"varint,5,opt,name=sms,proto3" json:"sms,omitempty"`
	Email                bool                 `protobuf:"varint,6,opt,name=email,proto3" json:"email,omitempty"`
	Temperature          bool                 `protobuf:"varint,7,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Humadity             bool                 `protobuf:"varint,8,opt,name=humadity,proto3" json:"humadity,omitempty"`
	Ec                   bool                 `protobuf:"varint,9,opt,name=ec,proto3" json:"ec,omitempty"`
	Door                 bool                 `protobuf:"varint,10,opt,name=door,proto3" json:"door,omitempty"`
	WLeak                bool                 `protobuf:"varint,11,opt,name=w_leak,proto3" json:"w_leak,omitempty"`
	SubmissionDate       *timestamp.Timestamp `protobuf:"bytes,12,opt,name=submission_date,proto3" json:"submission_date,omitempty"`
	IpAddress            string               `protobuf:"bytes,13,opt,name=ip_address,proto3" json:"ip_address,omitempty"`
	IsTimeScheduled      bool                 `protobuf:"varint,14,opt,name=is_time_scheduled,proto3" json:"is_time_scheduled,omitempty"`
	StartTime            float32              `protobuf:"fixed32,15,opt,name=start_time,proto3" json:"start_time,omitempty"`
	EndTime              float32              `protobuf:"fixed32,16,opt,name=end_time,proto3" json:"end_time,omitempty"`
	ZoneCategory         int64                `protobuf:"varint,17,opt,name=zone_category,proto3" json:"zone_category,omitempty"`
	ColdRoomTime         int64                `protobuf:"varint,18,opt,name=cold_room_time,proto3" json:"cold_room_time,omitempty"`
	ColdRoomFrecuancy    int64                `protobuf:"varint,19,opt,name=cold_room_frecuancy,proto3" json:"cold_room_frecuancy,omitempty"`
	Notification         bool                 `protobuf:"varint,20,opt,name=notification,proto3" json:"notification,omitempty"`
	AlarmDateTime        []*AlarmDateTime     `protobuf:"bytes,21,rep,name=alarm_date_time,proto3" json:"alarm_date_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Alarm) Reset()         { *m = Alarm{} }
func (m *Alarm) String() string { return proto.CompactTextString(m) }
func (*Alarm) ProtoMessage()    {}
func (*Alarm) Descriptor() ([]byte, []int) {
	return fileDescriptor_810c2ee2c60e0ebe, []int{0}
}

func (m *Alarm) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Alarm.Unmarshal(m, b)
}
func (m *Alarm) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Alarm.Marshal(b, m, deterministic)
}
func (m *Alarm) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Alarm.Merge(m, src)
}
func (m *Alarm) XXX_Size() int {
	return xxx_messageInfo_Alarm.Size(m)
}
func (m *Alarm) XXX_DiscardUnknown() {
	xxx_messageInfo_Alarm.DiscardUnknown(m)
}

var xxx_messageInfo_Alarm proto.InternalMessageInfo

func (m *Alarm) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Alarm) GetDevEui() string {
	if m != nil {
		return m.DevEui
	}
	return ""
}

func (m *Alarm) GetMinTreshold() float32 {
	if m != nil {
		return m.MinTreshold
	}
	return 0
}

func (m *Alarm) GetMaxTreshold() float32 {
	if m != nil {
		return m.MaxTreshold
	}
	return 0
}

func (m *Alarm) GetSms() bool {
	if m != nil {
		return m.Sms
	}
	return false
}

func (m *Alarm) GetEmail() bool {
	if m != nil {
		return m.Email
	}
	return false
}

func (m *Alarm) GetTemperature() bool {
	if m != nil {
		return m.Temperature
	}
	return false
}

func (m *Alarm) GetHumadity() bool {
	if m != nil {
		return m.Humadity
	}
	return false
}

func (m *Alarm) GetEc() bool {
	if m != nil {
		return m.Ec
	}
	return false
}

func (m *Alarm) GetDoor() bool {
	if m != nil {
		return m.Door
	}
	return false
}

func (m *Alarm) GetWLeak() bool {
	if m != nil {
		return m.WLeak
	}
	return false
}

func (m *Alarm) GetSubmissionDate() *timestamp.Timestamp {
	if m != nil {
		return m.SubmissionDate
	}
	return nil
}

func (m *Alarm) GetIpAddress() string {
	if m != nil {
		return m.IpAddress
	}
	return ""
}

func (m *Alarm) GetIsTimeScheduled() bool {
	if m != nil {
		return m.IsTimeScheduled
	}
	return false
}

func (m *Alarm) GetStartTime() float32 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *Alarm) GetEndTime() float32 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *Alarm) GetZoneCategory() int64 {
	if m != nil {
		return m.ZoneCategory
	}
	return 0
}

func (m *Alarm) GetColdRoomTime() int64 {
	if m != nil {
		return m.ColdRoomTime
	}
	return 0
}

func (m *Alarm) GetColdRoomFrecuancy() int64 {
	if m != nil {
		return m.ColdRoomFrecuancy
	}
	return 0
}

func (m *Alarm) GetNotification() bool {
	if m != nil {
		return m.Notification
	}
	return false
}

func (m *Alarm) GetAlarmDateTime() []*AlarmDateTime {
	if m != nil {
		return m.AlarmDateTime
	}
	return nil
}

type AlarmDateTime struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AlarmId              int64    `protobuf:"varint,2,opt,name=alarm_id,proto3" json:"alarm_id,omitempty"`
	AlarmDay             int64    `protobuf:"varint,3,opt,name=alarm_day,proto3" json:"alarm_day,omitempty"`
	AlarmStartTime       float32  `protobuf:"fixed32,4,opt,name=alarm_start_time,proto3" json:"alarm_start_time,omitempty"`
	AlarmEndTime         float32  `protobuf:"fixed32,5,opt,name=alarm_end_time,proto3" json:"alarm_end_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AlarmDateTime) Reset()         { *m = AlarmDateTime{} }
func (m *AlarmDateTime) String() string { return proto.CompactTextString(m) }
func (*AlarmDateTime) ProtoMessage()    {}
func (*AlarmDateTime) Descriptor() ([]byte, []int) {
	return fileDescriptor_810c2ee2c60e0ebe, []int{1}
}

func (m *AlarmDateTime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AlarmDateTime.Unmarshal(m, b)
}
func (m *AlarmDateTime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AlarmDateTime.Marshal(b, m, deterministic)
}
func (m *AlarmDateTime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AlarmDateTime.Merge(m, src)
}
func (m *AlarmDateTime) XXX_Size() int {
	return xxx_messageInfo_AlarmDateTime.Size(m)
}
func (m *AlarmDateTime) XXX_DiscardUnknown() {
	xxx_messageInfo_AlarmDateTime.DiscardUnknown(m)
}

var xxx_messageInfo_AlarmDateTime proto.InternalMessageInfo

func (m *AlarmDateTime) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AlarmDateTime) GetAlarmId() int64 {
	if m != nil {
		return m.AlarmId
	}
	return 0
}

func (m *AlarmDateTime) GetAlarmDay() int64 {
	if m != nil {
		return m.AlarmDay
	}
	return 0
}

func (m *AlarmDateTime) GetAlarmStartTime() float32 {
	if m != nil {
		return m.AlarmStartTime
	}
	return 0
}

func (m *AlarmDateTime) GetAlarmEndTime() float32 {
	if m != nil {
		return m.AlarmEndTime
	}
	return 0
}

type CreateAlarmResponse struct {
	Alarm                []*Alarm `protobuf:"bytes,1,rep,name=alarm,proto3" json:"alarm,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAlarmResponse) Reset()         { *m = CreateAlarmResponse{} }
func (m *CreateAlarmResponse) String() string { return proto.CompactTextString(m) }
func (*CreateAlarmResponse) ProtoMessage()    {}
func (*CreateAlarmResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_810c2ee2c60e0ebe, []int{2}
}

func (m *CreateAlarmResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAlarmResponse.Unmarshal(m, b)
}
func (m *CreateAlarmResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAlarmResponse.Marshal(b, m, deterministic)
}
func (m *CreateAlarmResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAlarmResponse.Merge(m, src)
}
func (m *CreateAlarmResponse) XXX_Size() int {
	return xxx_messageInfo_CreateAlarmResponse.Size(m)
}
func (m *CreateAlarmResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAlarmResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAlarmResponse proto.InternalMessageInfo

func (m *CreateAlarmResponse) GetAlarm() []*Alarm {
	if m != nil {
		return m.Alarm
	}
	return nil
}

type CreateAlarmRequest struct {
	CreateAlarm          []*Alarm `protobuf:"bytes,1,rep,name=create_alarm,json=createAlarm,proto3" json:"create_alarm,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAlarmRequest) Reset()         { *m = CreateAlarmRequest{} }
func (m *CreateAlarmRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAlarmRequest) ProtoMessage()    {}
func (*CreateAlarmRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_810c2ee2c60e0ebe, []int{3}
}

func (m *CreateAlarmRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAlarmRequest.Unmarshal(m, b)
}
func (m *CreateAlarmRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAlarmRequest.Marshal(b, m, deterministic)
}
func (m *CreateAlarmRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAlarmRequest.Merge(m, src)
}
func (m *CreateAlarmRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAlarmRequest.Size(m)
}
func (m *CreateAlarmRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAlarmRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAlarmRequest proto.InternalMessageInfo

func (m *CreateAlarmRequest) GetCreateAlarm() []*Alarm {
	if m != nil {
		return m.CreateAlarm
	}
	return nil
}

type CreateMultipleAlarmRequest struct {
	CreateAlarm          []*Alarm `protobuf:"bytes,1,rep,name=create_alarm,json=createAlarm,proto3" json:"create_alarm,omitempty"`
	UserIds              []int64  `protobuf:"varint,2,rep,packed,name=userIds,proto3" json:"userIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateMultipleAlarmRequest) Reset()         { *m = CreateMultipleAlarmRequest{} }
func (m *CreateMultipleAlarmRequest) String() string { return proto.CompactTextString(m) }
func (*CreateMultipleAlarmRequest) ProtoMessage()    {}
func (*CreateMultipleAlarmRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_810c2ee2c60e0ebe, []int{4}
}

func (m *CreateMultipleAlarmRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMultipleAlarmRequest.Unmarshal(m, b)
}
func (m *CreateMultipleAlarmRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMultipleAlarmRequest.Marshal(b, m, deterministic)
}
func (m *CreateMultipleAlarmRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMultipleAlarmRequest.Merge(m, src)
}
func (m *CreateMultipleAlarmRequest) XXX_Size() int {
	return xxx_messageInfo_CreateMultipleAlarmRequest.Size(m)
}
func (m *CreateMultipleAlarmRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMultipleAlarmRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMultipleAlarmRequest proto.InternalMessageInfo

func (m *CreateMultipleAlarmRequest) GetCreateAlarm() []*Alarm {
	if m != nil {
		return m.CreateAlarm
	}
	return nil
}

func (m *CreateMultipleAlarmRequest) GetUserIds() []int64 {
	if m != nil {
		return m.UserIds
	}
	return nil
}

type CreateAlarmMultipleResponse struct {
	Alarm                []*Alarm `protobuf:"bytes,1,rep,name=alarm,proto3" json:"alarm,omitempty"`
	UserIds              []int64  `protobuf:"varint,2,rep,packed,name=userIds,proto3" json:"userIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAlarmMultipleResponse) Reset()         { *m = CreateAlarmMultipleResponse{} }
func (m *CreateAlarmMultipleResponse) String() string { return proto.CompactTextString(m) }
func (*CreateAlarmMultipleResponse) ProtoMessage()    {}
func (*CreateAlarmMultipleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_810c2ee2c60e0ebe, []int{5}
}

func (m *CreateAlarmMultipleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAlarmMultipleResponse.Unmarshal(m, b)
}
func (m *CreateAlarmMultipleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAlarmMultipleResponse.Marshal(b, m, deterministic)
}
func (m *CreateAlarmMultipleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAlarmMultipleResponse.Merge(m, src)
}
func (m *CreateAlarmMultipleResponse) XXX_Size() int {
	return xxx_messageInfo_CreateAlarmMultipleResponse.Size(m)
}
func (m *CreateAlarmMultipleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAlarmMultipleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAlarmMultipleResponse proto.InternalMessageInfo

func (m *CreateAlarmMultipleResponse) GetAlarm() []*Alarm {
	if m != nil {
		return m.Alarm
	}
	return nil
}

func (m *CreateAlarmMultipleResponse) GetUserIds() []int64 {
	if m != nil {
		return m.UserIds
	}
	return nil
}

type GetAlarmRequest struct {
	// Device EUI (HEX encoded).
	AlarmId              string   `protobuf:"bytes,1,opt,name=alarm_id,json=alarmID,proto3" json:"alarm_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAlarmRequest) Reset()         { *m = GetAlarmRequest{} }
func (m *GetAlarmRequest) String() string { return proto.CompactTextString(m) }
func (*GetAlarmRequest) ProtoMessage()    {}
func (*GetAlarmRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_810c2ee2c60e0ebe, []int{6}
}

func (m *GetAlarmRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAlarmRequest.Unmarshal(m, b)
}
func (m *GetAlarmRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAlarmRequest.Marshal(b, m, deterministic)
}
func (m *GetAlarmRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAlarmRequest.Merge(m, src)
}
func (m *GetAlarmRequest) XXX_Size() int {
	return xxx_messageInfo_GetAlarmRequest.Size(m)
}
func (m *GetAlarmRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAlarmRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAlarmRequest proto.InternalMessageInfo

func (m *GetAlarmRequest) GetAlarmId() string {
	if m != nil {
		return m.AlarmId
	}
	return ""
}

type GetAlarmResponse struct {
	// Alarm object
	Alarm                *Alarm   `protobuf:"bytes,1,opt,name=alarm,proto3" json:"alarm,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAlarmResponse) Reset()         { *m = GetAlarmResponse{} }
func (m *GetAlarmResponse) String() string { return proto.CompactTextString(m) }
func (*GetAlarmResponse) ProtoMessage()    {}
func (*GetAlarmResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_810c2ee2c60e0ebe, []int{7}
}

func (m *GetAlarmResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAlarmResponse.Unmarshal(m, b)
}
func (m *GetAlarmResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAlarmResponse.Marshal(b, m, deterministic)
}
func (m *GetAlarmResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAlarmResponse.Merge(m, src)
}
func (m *GetAlarmResponse) XXX_Size() int {
	return xxx_messageInfo_GetAlarmResponse.Size(m)
}
func (m *GetAlarmResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAlarmResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAlarmResponse proto.InternalMessageInfo

func (m *GetAlarmResponse) GetAlarm() *Alarm {
	if m != nil {
		return m.Alarm
	}
	return nil
}

type DeleteAlarmRequest struct {
	// Alarm Id (HEX encoded).
	AlarmId              []string `protobuf:"bytes,1,rep,name=alarm_id,json=alarmID,proto3" json:"alarm_id,omitempty"`
	IpAddress            string   `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAlarmRequest) Reset()         { *m = DeleteAlarmRequest{} }
func (m *DeleteAlarmRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAlarmRequest) ProtoMessage()    {}
func (*DeleteAlarmRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_810c2ee2c60e0ebe, []int{8}
}

func (m *DeleteAlarmRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAlarmRequest.Unmarshal(m, b)
}
func (m *DeleteAlarmRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAlarmRequest.Marshal(b, m, deterministic)
}
func (m *DeleteAlarmRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAlarmRequest.Merge(m, src)
}
func (m *DeleteAlarmRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteAlarmRequest.Size(m)
}
func (m *DeleteAlarmRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAlarmRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAlarmRequest proto.InternalMessageInfo

func (m *DeleteAlarmRequest) GetAlarmId() []string {
	if m != nil {
		return m.AlarmId
	}
	return nil
}

func (m *DeleteAlarmRequest) GetIpAddress() string {
	if m != nil {
		return m.IpAddress
	}
	return ""
}

type ListOrganizationAlarmRequest struct {
	// Max number of devices to return in the result-set.
	Limit int64 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	// Offset in the result-set (for pagination).
	Offset int64 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	// Device EUI (HEX encoded).
	DevEui               string   `protobuf:"bytes,3,opt,name=dev_eui,json=devEUI,proto3" json:"dev_eui,omitempty"`
	OrganizationId       int64    `protobuf:"varint,4,opt,name=organization_id,json=organizationID,proto3" json:"organization_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListOrganizationAlarmRequest) Reset()         { *m = ListOrganizationAlarmRequest{} }
func (m *ListOrganizationAlarmRequest) String() string { return proto.CompactTextString(m) }
func (*ListOrganizationAlarmRequest) ProtoMessage()    {}
func (*ListOrganizationAlarmRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_810c2ee2c60e0ebe, []int{9}
}

func (m *ListOrganizationAlarmRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOrganizationAlarmRequest.Unmarshal(m, b)
}
func (m *ListOrganizationAlarmRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOrganizationAlarmRequest.Marshal(b, m, deterministic)
}
func (m *ListOrganizationAlarmRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOrganizationAlarmRequest.Merge(m, src)
}
func (m *ListOrganizationAlarmRequest) XXX_Size() int {
	return xxx_messageInfo_ListOrganizationAlarmRequest.Size(m)
}
func (m *ListOrganizationAlarmRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOrganizationAlarmRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListOrganizationAlarmRequest proto.InternalMessageInfo

func (m *ListOrganizationAlarmRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListOrganizationAlarmRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ListOrganizationAlarmRequest) GetDevEui() string {
	if m != nil {
		return m.DevEui
	}
	return ""
}

func (m *ListOrganizationAlarmRequest) GetOrganizationId() int64 {
	if m != nil {
		return m.OrganizationId
	}
	return 0
}

type DeleteMultipleAlarmRequest struct {
	// Alarm Id (HEX encoded).
	UserId               []int64  `protobuf:"varint,1,rep,packed,name=user_id,json=userIDs,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMultipleAlarmRequest) Reset()         { *m = DeleteMultipleAlarmRequest{} }
func (m *DeleteMultipleAlarmRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteMultipleAlarmRequest) ProtoMessage()    {}
func (*DeleteMultipleAlarmRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_810c2ee2c60e0ebe, []int{10}
}

func (m *DeleteMultipleAlarmRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMultipleAlarmRequest.Unmarshal(m, b)
}
func (m *DeleteMultipleAlarmRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMultipleAlarmRequest.Marshal(b, m, deterministic)
}
func (m *DeleteMultipleAlarmRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMultipleAlarmRequest.Merge(m, src)
}
func (m *DeleteMultipleAlarmRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteMultipleAlarmRequest.Size(m)
}
func (m *DeleteMultipleAlarmRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMultipleAlarmRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMultipleAlarmRequest proto.InternalMessageInfo

func (m *DeleteMultipleAlarmRequest) GetUserId() []int64 {
	if m != nil {
		return m.UserId
	}
	return nil
}

type ListOrganizationAlarmResponse struct {
	// Alarm id.
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Device EUI (HEX encoded).
	DevEui string `protobuf:"bytes,2,opt,name=dev_eui,json=devEUI,proto3" json:"dev_eui,omitempty"`
	// Device EUI (HEX encoded).
	DeviceName string `protobuf:"bytes,3,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	// Device EUI (HEX encoded).
	ZoneName string `protobuf:"bytes,4,opt,name=zone_name,json=zoneName,proto3" json:"zone_name,omitempty"`
	// Condition of alarm
	MinTreshold float32 `protobuf:"fixed32,5,opt,name=min_treshold,json=minTreshold,proto3" json:"min_treshold,omitempty"`
	// Value of alarm
	MaxTreshold          float32              `protobuf:"fixed32,6,opt,name=max_treshold,json=maxTreshold,proto3" json:"max_treshold,omitempty"`
	Sms                  bool                 `protobuf:"varint,7,opt,name=sms,proto3" json:"sms,omitempty"`
	Email                bool                 `protobuf:"varint,8,opt,name=email,proto3" json:"email,omitempty"`
	Temperature          bool                 `protobuf:"varint,9,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Humadity             bool                 `protobuf:"varint,10,opt,name=humadity,proto3" json:"humadity,omitempty"`
	Ec                   bool                 `protobuf:"varint,11,opt,name=ec,proto3" json:"ec,omitempty"`
	Door                 bool                 `protobuf:"varint,12,opt,name=door,proto3" json:"door,omitempty"`
	WLeak                bool                 `protobuf:"varint,13,opt,name=w_leak,proto3" json:"w_leak,omitempty"`
	SubmissionDate       *timestamp.Timestamp `protobuf:"bytes,14,opt,name=submission_date,proto3" json:"submission_date,omitempty"`
	IsTimeScheduled      bool                 `protobuf:"varint,15,opt,name=is_time_scheduled,proto3" json:"is_time_scheduled,omitempty"`
	Notification         bool                 `protobuf:"varint,16,opt,name=notification,proto3" json:"notification,omitempty"`
	AlarmDateTime        []*AlarmDateTime     `protobuf:"bytes,17,rep,name=alarm_date_time,proto3" json:"alarm_date_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ListOrganizationAlarmResponse) Reset()         { *m = ListOrganizationAlarmResponse{} }
func (m *ListOrganizationAlarmResponse) String() string { return proto.CompactTextString(m) }
func (*ListOrganizationAlarmResponse) ProtoMessage()    {}
func (*ListOrganizationAlarmResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_810c2ee2c60e0ebe, []int{11}
}

func (m *ListOrganizationAlarmResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOrganizationAlarmResponse.Unmarshal(m, b)
}
func (m *ListOrganizationAlarmResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOrganizationAlarmResponse.Marshal(b, m, deterministic)
}
func (m *ListOrganizationAlarmResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOrganizationAlarmResponse.Merge(m, src)
}
func (m *ListOrganizationAlarmResponse) XXX_Size() int {
	return xxx_messageInfo_ListOrganizationAlarmResponse.Size(m)
}
func (m *ListOrganizationAlarmResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOrganizationAlarmResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListOrganizationAlarmResponse proto.InternalMessageInfo

func (m *ListOrganizationAlarmResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ListOrganizationAlarmResponse) GetDevEui() string {
	if m != nil {
		return m.DevEui
	}
	return ""
}

func (m *ListOrganizationAlarmResponse) GetDeviceName() string {
	if m != nil {
		return m.DeviceName
	}
	return ""
}

func (m *ListOrganizationAlarmResponse) GetZoneName() string {
	if m != nil {
		return m.ZoneName
	}
	return ""
}

func (m *ListOrganizationAlarmResponse) GetMinTreshold() float32 {
	if m != nil {
		return m.MinTreshold
	}
	return 0
}

func (m *ListOrganizationAlarmResponse) GetMaxTreshold() float32 {
	if m != nil {
		return m.MaxTreshold
	}
	return 0
}

func (m *ListOrganizationAlarmResponse) GetSms() bool {
	if m != nil {
		return m.Sms
	}
	return false
}

func (m *ListOrganizationAlarmResponse) GetEmail() bool {
	if m != nil {
		return m.Email
	}
	return false
}

func (m *ListOrganizationAlarmResponse) GetTemperature() bool {
	if m != nil {
		return m.Temperature
	}
	return false
}

func (m *ListOrganizationAlarmResponse) GetHumadity() bool {
	if m != nil {
		return m.Humadity
	}
	return false
}

func (m *ListOrganizationAlarmResponse) GetEc() bool {
	if m != nil {
		return m.Ec
	}
	return false
}

func (m *ListOrganizationAlarmResponse) GetDoor() bool {
	if m != nil {
		return m.Door
	}
	return false
}

func (m *ListOrganizationAlarmResponse) GetWLeak() bool {
	if m != nil {
		return m.WLeak
	}
	return false
}

func (m *ListOrganizationAlarmResponse) GetSubmissionDate() *timestamp.Timestamp {
	if m != nil {
		return m.SubmissionDate
	}
	return nil
}

func (m *ListOrganizationAlarmResponse) GetIsTimeScheduled() bool {
	if m != nil {
		return m.IsTimeScheduled
	}
	return false
}

func (m *ListOrganizationAlarmResponse) GetNotification() bool {
	if m != nil {
		return m.Notification
	}
	return false
}

func (m *ListOrganizationAlarmResponse) GetAlarmDateTime() []*AlarmDateTime {
	if m != nil {
		return m.AlarmDateTime
	}
	return nil
}

type UpdateAlarmRequest struct {
	// Alarm object to update.
	Alarm                *Alarm   `protobuf:"bytes,1,opt,name=alarm,proto3" json:"alarm,omitempty"`
	AlarmId              string   `protobuf:"bytes,2,opt,name=alarm_id,json=alarmID,proto3" json:"alarm_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateAlarmRequest) Reset()         { *m = UpdateAlarmRequest{} }
func (m *UpdateAlarmRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateAlarmRequest) ProtoMessage()    {}
func (*UpdateAlarmRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_810c2ee2c60e0ebe, []int{12}
}

func (m *UpdateAlarmRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAlarmRequest.Unmarshal(m, b)
}
func (m *UpdateAlarmRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAlarmRequest.Marshal(b, m, deterministic)
}
func (m *UpdateAlarmRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAlarmRequest.Merge(m, src)
}
func (m *UpdateAlarmRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateAlarmRequest.Size(m)
}
func (m *UpdateAlarmRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAlarmRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAlarmRequest proto.InternalMessageInfo

func (m *UpdateAlarmRequest) GetAlarm() *Alarm {
	if m != nil {
		return m.Alarm
	}
	return nil
}

func (m *UpdateAlarmRequest) GetAlarmId() string {
	if m != nil {
		return m.AlarmId
	}
	return ""
}

type ListAlarmRequest struct {
	// Max number of devices to return in the result-set.
	Limit int64 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	// Offset in the result-set (for pagination).
	Offset int64 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	// Device EUI (HEX encoded).
	DevEui string `protobuf:"bytes,3,opt,name=dev_eui,json=devEUI,proto3" json:"dev_eui,omitempty"`
	// Offset in the result-set (for pagination).
	UserId               int64    `protobuf:"varint,4,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListAlarmRequest) Reset()         { *m = ListAlarmRequest{} }
func (m *ListAlarmRequest) String() string { return proto.CompactTextString(m) }
func (*ListAlarmRequest) ProtoMessage()    {}
func (*ListAlarmRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_810c2ee2c60e0ebe, []int{13}
}

func (m *ListAlarmRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAlarmRequest.Unmarshal(m, b)
}
func (m *ListAlarmRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAlarmRequest.Marshal(b, m, deterministic)
}
func (m *ListAlarmRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAlarmRequest.Merge(m, src)
}
func (m *ListAlarmRequest) XXX_Size() int {
	return xxx_messageInfo_ListAlarmRequest.Size(m)
}
func (m *ListAlarmRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAlarmRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListAlarmRequest proto.InternalMessageInfo

func (m *ListAlarmRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListAlarmRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ListAlarmRequest) GetDevEui() string {
	if m != nil {
		return m.DevEui
	}
	return ""
}

func (m *ListAlarmRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type ListAlarmResponse struct {
	// Total number of devices available within the result-set.
	TotalCount int64 `protobuf:"varint,1,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	// Devices within this result-set.
	Result               []*Alarm     `protobuf:"bytes,2,rep,name=result,proto3" json:"result,omitempty"`
	Logs                 []*AlarmLogs `protobuf:"bytes,3,rep,name=logs,proto3" json:"logs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ListAlarmResponse) Reset()         { *m = ListAlarmResponse{} }
func (m *ListAlarmResponse) String() string { return proto.CompactTextString(m) }
func (*ListAlarmResponse) ProtoMessage()    {}
func (*ListAlarmResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_810c2ee2c60e0ebe, []int{14}
}

func (m *ListAlarmResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAlarmResponse.Unmarshal(m, b)
}
func (m *ListAlarmResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAlarmResponse.Marshal(b, m, deterministic)
}
func (m *ListAlarmResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAlarmResponse.Merge(m, src)
}
func (m *ListAlarmResponse) XXX_Size() int {
	return xxx_messageInfo_ListAlarmResponse.Size(m)
}
func (m *ListAlarmResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAlarmResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListAlarmResponse proto.InternalMessageInfo

func (m *ListAlarmResponse) GetTotalCount() int64 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func (m *ListAlarmResponse) GetResult() []*Alarm {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *ListAlarmResponse) GetLogs() []*AlarmLogs {
	if m != nil {
		return m.Logs
	}
	return nil
}

type ListORganizationAlarmResponse struct {
	// Total number of devices available within the result-set.
	TotalCount           int64    `protobuf:"varint,1,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListORganizationAlarmResponse) Reset()         { *m = ListORganizationAlarmResponse{} }
func (m *ListORganizationAlarmResponse) String() string { return proto.CompactTextString(m) }
func (*ListORganizationAlarmResponse) ProtoMessage()    {}
func (*ListORganizationAlarmResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_810c2ee2c60e0ebe, []int{15}
}

func (m *ListORganizationAlarmResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListORganizationAlarmResponse.Unmarshal(m, b)
}
func (m *ListORganizationAlarmResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListORganizationAlarmResponse.Marshal(b, m, deterministic)
}
func (m *ListORganizationAlarmResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListORganizationAlarmResponse.Merge(m, src)
}
func (m *ListORganizationAlarmResponse) XXX_Size() int {
	return xxx_messageInfo_ListORganizationAlarmResponse.Size(m)
}
func (m *ListORganizationAlarmResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListORganizationAlarmResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListORganizationAlarmResponse proto.InternalMessageInfo

func (m *ListORganizationAlarmResponse) GetTotalCount() int64 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

type AlarmLogs struct {
	DevEui string `protobuf:"bytes,1,opt,name=dev_eui,json=devEUI,proto3" json:"dev_eui,omitempty"`
	// Condition of alarm
	MinTreshold float32 `protobuf:"fixed32,2,opt,name=min_treshold,json=minTreshold,proto3" json:"min_treshold,omitempty"`
	// Value of alarm
	MaxTreshold          float32              `protobuf:"fixed32,3,opt,name=max_treshold,json=maxTreshold,proto3" json:"max_treshold,omitempty"`
	UserId               int64                `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IpAddress            string               `protobuf:"bytes,5,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	IsDeleted            int64                `protobuf:"varint,6,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	Temperature          bool                 `protobuf:"varint,7,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Humadity             bool                 `protobuf:"varint,8,opt,name=humadity,proto3" json:"humadity,omitempty"`
	Ec                   bool                 `protobuf:"varint,9,opt,name=ec,proto3" json:"ec,omitempty"`
	Door                 bool                 `protobuf:"varint,10,opt,name=door,proto3" json:"door,omitempty"`
	WLeak                bool                 `protobuf:"varint,11,opt,name=w_leak,proto3" json:"w_leak,omitempty"`
	Sms                  bool                 `protobuf:"varint,12,opt,name=sms,proto3" json:"sms,omitempty"`
	SubmissionDate       *timestamp.Timestamp `protobuf:"bytes,13,opt,name=submission_date,json=submissionDate,proto3" json:"submission_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *AlarmLogs) Reset()         { *m = AlarmLogs{} }
func (m *AlarmLogs) String() string { return proto.CompactTextString(m) }
func (*AlarmLogs) ProtoMessage()    {}
func (*AlarmLogs) Descriptor() ([]byte, []int) {
	return fileDescriptor_810c2ee2c60e0ebe, []int{16}
}

func (m *AlarmLogs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AlarmLogs.Unmarshal(m, b)
}
func (m *AlarmLogs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AlarmLogs.Marshal(b, m, deterministic)
}
func (m *AlarmLogs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AlarmLogs.Merge(m, src)
}
func (m *AlarmLogs) XXX_Size() int {
	return xxx_messageInfo_AlarmLogs.Size(m)
}
func (m *AlarmLogs) XXX_DiscardUnknown() {
	xxx_messageInfo_AlarmLogs.DiscardUnknown(m)
}

var xxx_messageInfo_AlarmLogs proto.InternalMessageInfo

func (m *AlarmLogs) GetDevEui() string {
	if m != nil {
		return m.DevEui
	}
	return ""
}

func (m *AlarmLogs) GetMinTreshold() float32 {
	if m != nil {
		return m.MinTreshold
	}
	return 0
}

func (m *AlarmLogs) GetMaxTreshold() float32 {
	if m != nil {
		return m.MaxTreshold
	}
	return 0
}

func (m *AlarmLogs) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *AlarmLogs) GetIpAddress() string {
	if m != nil {
		return m.IpAddress
	}
	return ""
}

func (m *AlarmLogs) GetIsDeleted() int64 {
	if m != nil {
		return m.IsDeleted
	}
	return 0
}

func (m *AlarmLogs) GetTemperature() bool {
	if m != nil {
		return m.Temperature
	}
	return false
}

func (m *AlarmLogs) GetHumadity() bool {
	if m != nil {
		return m.Humadity
	}
	return false
}

func (m *AlarmLogs) GetEc() bool {
	if m != nil {
		return m.Ec
	}
	return false
}

func (m *AlarmLogs) GetDoor() bool {
	if m != nil {
		return m.Door
	}
	return false
}

func (m *AlarmLogs) GetWLeak() bool {
	if m != nil {
		return m.WLeak
	}
	return false
}

func (m *AlarmLogs) GetSms() bool {
	if m != nil {
		return m.Sms
	}
	return false
}

func (m *AlarmLogs) GetSubmissionDate() *timestamp.Timestamp {
	if m != nil {
		return m.SubmissionDate
	}
	return nil
}

func init() {
	proto.RegisterType((*Alarm)(nil), "als.Alarm")
	proto.RegisterType((*AlarmDateTime)(nil), "als.AlarmDateTime")
	proto.RegisterType((*CreateAlarmResponse)(nil), "als.CreateAlarmResponse")
	proto.RegisterType((*CreateAlarmRequest)(nil), "als.CreateAlarmRequest")
	proto.RegisterType((*CreateMultipleAlarmRequest)(nil), "als.CreateMultipleAlarmRequest")
	proto.RegisterType((*CreateAlarmMultipleResponse)(nil), "als.CreateAlarmMultipleResponse")
	proto.RegisterType((*GetAlarmRequest)(nil), "als.GetAlarmRequest")
	proto.RegisterType((*GetAlarmResponse)(nil), "als.GetAlarmResponse")
	proto.RegisterType((*DeleteAlarmRequest)(nil), "als.DeleteAlarmRequest")
	proto.RegisterType((*ListOrganizationAlarmRequest)(nil), "als.ListOrganizationAlarmRequest")
	proto.RegisterType((*DeleteMultipleAlarmRequest)(nil), "als.DeleteMultipleAlarmRequest")
	proto.RegisterType((*ListOrganizationAlarmResponse)(nil), "als.ListOrganizationAlarmResponse")
	proto.RegisterType((*UpdateAlarmRequest)(nil), "als.UpdateAlarmRequest")
	proto.RegisterType((*ListAlarmRequest)(nil), "als.ListAlarmRequest")
	proto.RegisterType((*ListAlarmResponse)(nil), "als.ListAlarmResponse")
	proto.RegisterType((*ListORganizationAlarmResponse)(nil), "als.ListORganizationAlarmResponse")
	proto.RegisterType((*AlarmLogs)(nil), "als.AlarmLogs")
}

func init() {
	proto.RegisterFile("als/als.proto", fileDescriptor_810c2ee2c60e0ebe)
}

var fileDescriptor_810c2ee2c60e0ebe = []byte{
	// 1228 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x57, 0xdb, 0x6e, 0xdb, 0x46,
	0x10, 0x0d, 0x45, 0x49, 0xb6, 0x46, 0xb2, 0x2c, 0xaf, 0x1d, 0x87, 0x65, 0x2e, 0x56, 0x88, 0xa2,
	0x15, 0x8a, 0x44, 0x2a, 0xd2, 0xa0, 0x01, 0x7a, 0x01, 0x9a, 0x5a, 0x41, 0x60, 0x34, 0x4d, 0x51,
	0x36, 0x79, 0x68, 0x5f, 0x88, 0x35, 0xb9, 0x96, 0x16, 0x21, 0xb9, 0x0c, 0x77, 0x99, 0xc6, 0x41,
	0xbf, 0xa1, 0x0f, 0xfd, 0x8f, 0xbe, 0xf4, 0x1b, 0xfa, 0xd4, 0xaf, 0x2a, 0xb8, 0x4b, 0x89, 0x37,
	0x5d, 0x5c, 0x14, 0x45, 0x9f, 0xec, 0x3d, 0x33, 0x3b, 0xbb, 0x33, 0x3b, 0x67, 0x0e, 0x05, 0x7b,
	0xd8, 0xe7, 0x13, 0xec, 0xf3, 0x71, 0x14, 0x33, 0xc1, 0x90, 0x8e, 0x7d, 0x6e, 0x9e, 0xcc, 0x18,
	0x9b, 0xf9, 0x64, 0x22, 0xa1, 0xf3, 0xe4, 0x62, 0x22, 0x68, 0x40, 0xb8, 0xc0, 0x41, 0xa4, 0xbc,
	0xcc, 0x9b, 0x55, 0x07, 0x12, 0x44, 0xe2, 0x32, 0x33, 0xde, 0xa9, 0x1a, 0xbd, 0x24, 0xc6, 0x82,
	0xb2, 0x30, 0xb3, 0x1f, 0xba, 0x2c, 0x08, 0x58, 0x38, 0x51, 0x7f, 0x14, 0x68, 0xfd, 0xd5, 0x82,
	0xd6, 0x63, 0x1f, 0xc7, 0x01, 0xea, 0x43, 0x83, 0x7a, 0x86, 0x36, 0xd4, 0x46, 0xba, 0xdd, 0xa0,
	0x1e, 0xba, 0x01, 0x3b, 0x1e, 0x79, 0xe3, 0x90, 0x84, 0x1a, 0x8d, 0xa1, 0x36, 0xea, 0xd8, 0x6d,
	0x8f, 0xbc, 0x79, 0xf2, 0xf2, 0x0c, 0xdd, 0x85, 0x5e, 0x40, 0x43, 0x47, 0xc4, 0x84, 0xcf, 0x99,
	0xef, 0x19, 0xfa, 0x50, 0x1b, 0x35, 0xec, 0x6e, 0x40, 0xc3, 0x17, 0x19, 0x24, 0x5d, 0xf0, 0xdb,
	0xdc, 0xa5, 0x99, 0xb9, 0xe0, 0xb7, 0x4b, 0x97, 0x01, 0xe8, 0x3c, 0xe0, 0x46, 0x6b, 0xa8, 0x8d,
	0x76, 0xed, 0xf4, 0x5f, 0x74, 0x04, 0x2d, 0x12, 0x60, 0xea, 0x1b, 0x6d, 0x89, 0xa9, 0x05, 0x1a,
	0x42, 0x57, 0x90, 0x20, 0x22, 0x31, 0x16, 0x49, 0x4c, 0x8c, 0x1d, 0x69, 0x2b, 0x42, 0xc8, 0x84,
	0xdd, 0x79, 0x12, 0x60, 0x8f, 0x8a, 0x4b, 0x63, 0x57, 0x9a, 0x97, 0xeb, 0x34, 0x29, 0xe2, 0x1a,
	0x1d, 0x89, 0x36, 0x88, 0x8b, 0x10, 0x34, 0x3d, 0xc6, 0x62, 0x03, 0x24, 0x22, 0xff, 0x47, 0xc7,
	0xd0, 0xfe, 0xd9, 0xf1, 0x09, 0x7e, 0x65, 0x74, 0x25, 0x9a, 0xad, 0xd0, 0x14, 0xf6, 0x79, 0x72,
	0x1e, 0x50, 0xce, 0x29, 0x0b, 0x1d, 0x0f, 0x0b, 0x62, 0xf4, 0x86, 0xda, 0xa8, 0xfb, 0xc0, 0x1c,
	0xab, 0x4a, 0x8f, 0x17, 0x95, 0x1e, 0xbf, 0x58, 0xbc, 0x93, 0x5d, 0xdd, 0x82, 0xee, 0x00, 0xd0,
	0xc8, 0xc1, 0x9e, 0x17, 0x13, 0xce, 0x8d, 0x3d, 0x59, 0xc9, 0x02, 0x82, 0xee, 0xc1, 0x01, 0xe5,
	0x4e, 0xfa, 0xd0, 0x0e, 0x77, 0xe7, 0xc4, 0x4b, 0x7c, 0xe2, 0x19, 0x7d, 0x79, 0x91, 0xba, 0x21,
	0x8d, 0xc6, 0x05, 0x8e, 0x85, 0xc4, 0x8d, 0x7d, 0x59, 0xd6, 0x02, 0x92, 0xd6, 0x82, 0x84, 0x9e,
	0xb2, 0x0e, 0xa4, 0x75, 0xb9, 0x46, 0xef, 0xc3, 0xde, 0x3b, 0x16, 0x12, 0xc7, 0xc5, 0x82, 0xcc,
	0x58, 0x7c, 0x69, 0x1c, 0xc8, 0xb7, 0x2e, 0x83, 0xe8, 0x03, 0xe8, 0xbb, 0xcc, 0xf7, 0x9c, 0x98,
	0xb1, 0x40, 0xc5, 0x41, 0xd2, 0xad, 0x82, 0xa2, 0x8f, 0xe1, 0x30, 0x47, 0x2e, 0x62, 0xe2, 0x26,
	0x38, 0x74, 0x2f, 0x8d, 0x43, 0xe9, 0xbc, 0xca, 0x84, 0x2c, 0xe8, 0x85, 0x4c, 0xd0, 0x0b, 0xea,
	0xca, 0xae, 0x34, 0x8e, 0x64, 0x92, 0x25, 0x0c, 0x7d, 0x01, 0xfb, 0x38, 0xed, 0x46, 0x59, 0x3b,
	0x75, 0xfc, 0xf5, 0xa1, 0x3e, 0xea, 0x3e, 0x40, 0xe3, 0x94, 0x2b, 0xb2, 0x53, 0xa7, 0x58, 0x90,
	0xb4, 0xe0, 0x76, 0xd5, 0xd5, 0xfa, 0x5d, 0x83, 0xbd, 0x92, 0x4b, 0xad, 0xa9, 0x4d, 0xd8, 0x55,
	0x9b, 0xa8, 0x27, 0xbb, 0x5a, 0xb7, 0x97, 0x6b, 0x74, 0x0b, 0x3a, 0x8b, 0x80, 0x97, 0xb2, 0xa9,
	0x75, 0x3b, 0x07, 0xd0, 0x47, 0x30, 0x50, 0x8b, 0x42, 0xfd, 0x55, 0x5b, 0xd7, 0xf0, 0xb4, 0x86,
	0x0a, 0x5b, 0xbe, 0x45, 0x4b, 0x7a, 0x56, 0x50, 0xeb, 0x11, 0x1c, 0x9e, 0xc6, 0x04, 0x0b, 0x22,
	0x2f, 0x6d, 0x13, 0x1e, 0xb1, 0x90, 0x13, 0x34, 0x84, 0x96, 0x74, 0x34, 0x34, 0x99, 0x3a, 0xe4,
	0xa9, 0xdb, 0xca, 0x60, 0x9d, 0x02, 0x2a, 0x6d, 0x7c, 0x9d, 0x10, 0x2e, 0xd0, 0x7d, 0xe8, 0xb9,
	0x12, 0x75, 0xd6, 0x6d, 0xef, 0xba, 0xf9, 0x2e, 0x8b, 0x80, 0xa9, 0x82, 0x7c, 0x9b, 0xf8, 0x82,
	0x46, 0xfe, 0xbf, 0x09, 0x86, 0x0c, 0xd8, 0x49, 0x38, 0x89, 0xcf, 0x3c, 0x6e, 0x34, 0x86, 0xfa,
	0x48, 0xb7, 0x17, 0x4b, 0xeb, 0x47, 0xb8, 0x59, 0xb8, 0xeb, 0xe2, 0xac, 0xab, 0x27, 0xbb, 0x21,
	0xf4, 0x3d, 0xd8, 0x7f, 0x4a, 0x44, 0xe9, 0xda, 0xef, 0x15, 0x1e, 0x58, 0x93, 0x64, 0xdb, 0x91,
	0xeb, 0xb3, 0xa9, 0xf5, 0x10, 0x06, 0xb9, 0x77, 0xfd, 0x74, 0x6d, 0x75, 0xa9, 0x9f, 0x03, 0x9a,
	0x12, 0x9f, 0x54, 0x4a, 0x5d, 0x3e, 0x46, 0x2f, 0x1c, 0x83, 0x6e, 0x97, 0x08, 0xaf, 0x46, 0x67,
	0x87, 0x46, 0x8f, 0x15, 0x60, 0xfd, 0xaa, 0xc1, 0xad, 0x67, 0x94, 0x8b, 0xef, 0xe2, 0x19, 0x0e,
	0xe9, 0x3b, 0xd9, 0xf6, 0xa5, 0xd0, 0x47, 0xd0, 0xf2, 0x69, 0x40, 0x45, 0xd6, 0xb5, 0x6a, 0x91,
	0x0e, 0x29, 0x76, 0x71, 0xc1, 0x89, 0xc8, 0xda, 0x36, 0x5b, 0x15, 0xa7, 0xb4, 0x5e, 0x9a, 0xd2,
	0x1f, 0xc2, 0x3e, 0x2b, 0x1c, 0x91, 0x5e, 0xb4, 0xa9, 0x88, 0x5c, 0x84, 0xcf, 0xa6, 0xd6, 0xa7,
	0x60, 0xaa, 0x04, 0x57, 0xb6, 0x41, 0x56, 0xfc, 0x45, 0x9e, 0x8b, 0xe2, 0x4f, 0xb9, 0xf5, 0x67,
	0x13, 0x6e, 0xaf, 0x49, 0x24, 0x2b, 0xee, 0x95, 0x15, 0xe5, 0x04, 0xba, 0x1e, 0x79, 0x43, 0x5d,
	0xe2, 0x84, 0x38, 0x20, 0x59, 0x22, 0xa0, 0xa0, 0xe7, 0x38, 0x20, 0xe8, 0x26, 0x74, 0xe4, 0x94,
	0x92, 0xe6, 0xa6, 0x34, 0xef, 0xa6, 0x80, 0x34, 0x56, 0xf5, 0xa8, 0xb5, 0x5d, 0x8f, 0xda, 0x6b,
	0xf5, 0x68, 0x67, 0x85, 0x1e, 0xed, 0x6e, 0xd0, 0xa3, 0xce, 0x66, 0x3d, 0x82, 0x95, 0x7a, 0xd4,
	0xad, 0xe9, 0x51, 0x6f, 0xa5, 0x1e, 0xed, 0x6d, 0xd3, 0xa3, 0xfe, 0x3f, 0xd7, 0xa3, 0x95, 0x7a,
	0xb3, 0xbf, 0x4e, 0x6f, 0xaa, 0x33, 0x7b, 0x70, 0xb5, 0x99, 0x7d, 0x70, 0xf5, 0x99, 0xfd, 0x3d,
	0xa0, 0x97, 0x91, 0x57, 0x1d, 0x65, 0x5b, 0x79, 0x59, 0x62, 0x60, 0xa3, 0x4c, 0xf4, 0xd7, 0x30,
	0x48, 0x1b, 0xf3, 0xbf, 0x60, 0xd5, 0x31, 0xb4, 0xd5, 0xf0, 0xc9, 0xc8, 0x94, 0xad, 0xac, 0x5f,
	0xe0, 0xa0, 0x70, 0x64, 0xd6, 0xff, 0x27, 0xd0, 0x15, 0x4c, 0x60, 0xdf, 0x71, 0x59, 0x12, 0x2e,
	0x4e, 0x06, 0x09, 0x9d, 0xa6, 0x08, 0xb2, 0xa0, 0x1d, 0x13, 0x9e, 0xf8, 0x42, 0x0e, 0xb6, 0x72,
	0x9a, 0x99, 0x05, 0x59, 0xd0, 0xf4, 0xd9, 0x8c, 0x1b, 0xba, 0xf4, 0xe8, 0xe7, 0x1e, 0xcf, 0xd8,
	0x8c, 0xdb, 0xd2, 0x66, 0x7d, 0x95, 0x31, 0xd1, 0x5e, 0xc7, 0xc4, 0x6d, 0x37, 0xb1, 0x7e, 0xd3,
	0xa1, 0xb3, 0x8c, 0x5a, 0x4c, 0x5f, 0xdb, 0xf8, 0xe9, 0xd7, 0xd8, 0x4e, 0x35, 0xbd, 0x4e, 0xb5,
	0x1b, 0xf9, 0x4c, 0x29, 0x55, 0xb1, 0x32, 0x3a, 0x5b, 0x95, 0xd1, 0x29, 0xcd, 0xdc, 0xf1, 0xe4,
	0xb0, 0x52, 0x1c, 0xd6, 0xed, 0x0e, 0xe5, 0x6a, 0x7a, 0x79, 0xff, 0xe3, 0x97, 0x62, 0x36, 0x3b,
	0x7a, 0xf9, 0xec, 0x38, 0xad, 0x73, 0x75, 0x6f, 0x2b, 0x57, 0xfb, 0xf9, 0x96, 0x94, 0x2f, 0x0f,
	0xfe, 0x68, 0x42, 0x4f, 0x3e, 0xca, 0x0f, 0x24, 0x4e, 0x47, 0x21, 0xfa, 0x12, 0xda, 0x4a, 0x4a,
	0xd1, 0x0d, 0xd9, 0x07, 0xf5, 0x6f, 0x00, 0xd3, 0xa8, 0x1b, 0x54, 0x0f, 0x58, 0xd7, 0xd0, 0x43,
	0xd0, 0x9f, 0x12, 0x81, 0x8e, 0xa4, 0x4b, 0x45, 0x38, 0xcd, 0xeb, 0x15, 0x74, 0xb9, 0xeb, 0x11,
	0x34, 0xd3, 0xe6, 0x42, 0xca, 0xa1, 0x4a, 0x2c, 0xf3, 0xb8, 0x0a, 0x2f, 0x37, 0x7e, 0x06, 0x6d,
	0xc5, 0xec, 0xec, 0xb6, 0x75, 0x9a, 0xaf, 0x3f, 0xf4, 0x73, 0x68, 0xab, 0x67, 0xcd, 0xf6, 0xd6,
	0x25, 0xd8, 0x3c, 0xae, 0x55, 0xf2, 0x49, 0xfa, 0x63, 0xc8, 0xba, 0x86, 0xbe, 0x81, 0x7e, 0xf9,
	0xc3, 0x06, 0x9d, 0x14, 0xaa, 0xb2, 0x4a, 0xe6, 0x36, 0x07, 0x2b, 0xcb, 0x63, 0x16, 0x6c, 0xbd,
	0x66, 0x6e, 0x08, 0x86, 0xe1, 0x78, 0xa5, 0x64, 0x72, 0x74, 0x77, 0x59, 0xc6, 0x75, 0x1f, 0x06,
	0xa6, 0x95, 0xbb, 0xac, 0x23, 0xba, 0x75, 0xed, 0xeb, 0x27, 0x70, 0x9d, 0xb2, 0xb1, 0x3b, 0xa7,
	0x71, 0xc4, 0x05, 0x76, 0x5f, 0x8d, 0x71, 0x44, 0xd3, 0x8d, 0x3f, 0xdd, 0x9b, 0x51, 0x31, 0x4f,
	0xce, 0xc7, 0x2e, 0x0b, 0x26, 0xf4, 0x3c, 0xc6, 0x73, 0x1a, 0xb0, 0x77, 0xe4, 0x15, 0x75, 0xe9,
	0x24, 0xf7, 0xbe, 0x8f, 0x23, 0x9a, 0xfe, 0x2a, 0x3d, 0x6f, 0xcb, 0xbb, 0x7f, 0xf2, 0x77, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x1b, 0xa6, 0x71, 0xf8, 0xa7, 0x0e, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AlarmServiceClient is the client API for AlarmService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AlarmServiceClient interface {
	// Create creates the alarm
	Create(ctx context.Context, in *CreateAlarmRequest, opts ...grpc.CallOption) (*CreateAlarmResponse, error)
	// Get return the alarm
	Get(ctx context.Context, in *GetAlarmRequest, opts ...grpc.CallOption) (*GetAlarmResponse, error)
	List(ctx context.Context, in *ListAlarmRequest, opts ...grpc.CallOption) (*ListAlarmResponse, error)
	// Update updates the alarm matching the given alarm_id.
	Update(ctx context.Context, in *UpdateAlarmRequest, opts ...grpc.CallOption) (*GetAlarmResponse, error)
	// Delete deletes the alarm matching the given alarm_id.
	Delete(ctx context.Context, in *DeleteAlarmRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Create creates the alarm
	CreateMultiple(ctx context.Context, in *CreateMultipleAlarmRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Delete deletes the alarm matching the given alarm_id.
	DeleteMultiple(ctx context.Context, in *DeleteMultipleAlarmRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// ListOrganizationAlarms ListOrganizationAlarms the alarm matching the given alarm_id.
	ListOrganizationAlarms(ctx context.Context, in *ListOrganizationAlarmRequest, opts ...grpc.CallOption) (*ListORganizationAlarmResponse, error)
}

type alarmServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAlarmServiceClient(cc grpc.ClientConnInterface) AlarmServiceClient {
	return &alarmServiceClient{cc}
}

func (c *alarmServiceClient) Create(ctx context.Context, in *CreateAlarmRequest, opts ...grpc.CallOption) (*CreateAlarmResponse, error) {
	out := new(CreateAlarmResponse)
	err := c.cc.Invoke(ctx, "/als.AlarmService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alarmServiceClient) Get(ctx context.Context, in *GetAlarmRequest, opts ...grpc.CallOption) (*GetAlarmResponse, error) {
	out := new(GetAlarmResponse)
	err := c.cc.Invoke(ctx, "/als.AlarmService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alarmServiceClient) List(ctx context.Context, in *ListAlarmRequest, opts ...grpc.CallOption) (*ListAlarmResponse, error) {
	out := new(ListAlarmResponse)
	err := c.cc.Invoke(ctx, "/als.AlarmService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alarmServiceClient) Update(ctx context.Context, in *UpdateAlarmRequest, opts ...grpc.CallOption) (*GetAlarmResponse, error) {
	out := new(GetAlarmResponse)
	err := c.cc.Invoke(ctx, "/als.AlarmService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alarmServiceClient) Delete(ctx context.Context, in *DeleteAlarmRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/als.AlarmService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alarmServiceClient) CreateMultiple(ctx context.Context, in *CreateMultipleAlarmRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/als.AlarmService/CreateMultiple", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alarmServiceClient) DeleteMultiple(ctx context.Context, in *DeleteMultipleAlarmRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/als.AlarmService/DeleteMultiple", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alarmServiceClient) ListOrganizationAlarms(ctx context.Context, in *ListOrganizationAlarmRequest, opts ...grpc.CallOption) (*ListORganizationAlarmResponse, error) {
	out := new(ListORganizationAlarmResponse)
	err := c.cc.Invoke(ctx, "/als.AlarmService/ListOrganizationAlarms", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AlarmServiceServer is the server API for AlarmService service.
type AlarmServiceServer interface {
	// Create creates the alarm
	Create(context.Context, *CreateAlarmRequest) (*CreateAlarmResponse, error)
	// Get return the alarm
	Get(context.Context, *GetAlarmRequest) (*GetAlarmResponse, error)
	List(context.Context, *ListAlarmRequest) (*ListAlarmResponse, error)
	// Update updates the alarm matching the given alarm_id.
	Update(context.Context, *UpdateAlarmRequest) (*GetAlarmResponse, error)
	// Delete deletes the alarm matching the given alarm_id.
	Delete(context.Context, *DeleteAlarmRequest) (*empty.Empty, error)
	// Create creates the alarm
	CreateMultiple(context.Context, *CreateMultipleAlarmRequest) (*empty.Empty, error)
	// Delete deletes the alarm matching the given alarm_id.
	DeleteMultiple(context.Context, *DeleteMultipleAlarmRequest) (*empty.Empty, error)
	// ListOrganizationAlarms ListOrganizationAlarms the alarm matching the given alarm_id.
	ListOrganizationAlarms(context.Context, *ListOrganizationAlarmRequest) (*ListORganizationAlarmResponse, error)
}

// UnimplementedAlarmServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAlarmServiceServer struct {
}

func (*UnimplementedAlarmServiceServer) Create(ctx context.Context, req *CreateAlarmRequest) (*CreateAlarmResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedAlarmServiceServer) Get(ctx context.Context, req *GetAlarmRequest) (*GetAlarmResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedAlarmServiceServer) List(ctx context.Context, req *ListAlarmRequest) (*ListAlarmResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedAlarmServiceServer) Update(ctx context.Context, req *UpdateAlarmRequest) (*GetAlarmResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedAlarmServiceServer) Delete(ctx context.Context, req *DeleteAlarmRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedAlarmServiceServer) CreateMultiple(ctx context.Context, req *CreateMultipleAlarmRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMultiple not implemented")
}
func (*UnimplementedAlarmServiceServer) DeleteMultiple(ctx context.Context, req *DeleteMultipleAlarmRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMultiple not implemented")
}
func (*UnimplementedAlarmServiceServer) ListOrganizationAlarms(ctx context.Context, req *ListOrganizationAlarmRequest) (*ListORganizationAlarmResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListOrganizationAlarms not implemented")
}

func RegisterAlarmServiceServer(s *grpc.Server, srv AlarmServiceServer) {
	s.RegisterService(&_AlarmService_serviceDesc, srv)
}

func _AlarmService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAlarmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlarmServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/als.AlarmService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlarmServiceServer).Create(ctx, req.(*CreateAlarmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlarmService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAlarmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlarmServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/als.AlarmService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlarmServiceServer).Get(ctx, req.(*GetAlarmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlarmService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAlarmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlarmServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/als.AlarmService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlarmServiceServer).List(ctx, req.(*ListAlarmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlarmService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAlarmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlarmServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/als.AlarmService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlarmServiceServer).Update(ctx, req.(*UpdateAlarmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlarmService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAlarmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlarmServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/als.AlarmService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlarmServiceServer).Delete(ctx, req.(*DeleteAlarmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlarmService_CreateMultiple_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMultipleAlarmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlarmServiceServer).CreateMultiple(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/als.AlarmService/CreateMultiple",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlarmServiceServer).CreateMultiple(ctx, req.(*CreateMultipleAlarmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlarmService_DeleteMultiple_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMultipleAlarmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlarmServiceServer).DeleteMultiple(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/als.AlarmService/DeleteMultiple",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlarmServiceServer).DeleteMultiple(ctx, req.(*DeleteMultipleAlarmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlarmService_ListOrganizationAlarms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOrganizationAlarmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlarmServiceServer).ListOrganizationAlarms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/als.AlarmService/ListOrganizationAlarms",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlarmServiceServer).ListOrganizationAlarms(ctx, req.(*ListOrganizationAlarmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AlarmService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "als.AlarmService",
	HandlerType: (*AlarmServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _AlarmService_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _AlarmService_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _AlarmService_List_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _AlarmService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _AlarmService_Delete_Handler,
		},
		{
			MethodName: "CreateMultiple",
			Handler:    _AlarmService_CreateMultiple_Handler,
		},
		{
			MethodName: "DeleteMultiple",
			Handler:    _AlarmService_DeleteMultiple_Handler,
		},
		{
			MethodName: "ListOrganizationAlarms",
			Handler:    _AlarmService_ListOrganizationAlarms_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "als/als.proto",
}
