// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ps/ps.proto

package ps

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Invoice struct {
	Id                   int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerID           int64                `protobuf:"varint,2,opt,name=customerID,proto3" json:"customerID,omitempty"`
	OrganizationID       int64                `protobuf:"varint,3,opt,name=organizationID,proto3" json:"organizationID,omitempty"`
	InvoiceDate          *timestamp.Timestamp `protobuf:"bytes,4,opt,name=invoiceDate,proto3" json:"invoiceDate,omitempty"`
	InvoiceNumber        string               `protobuf:"bytes,5,opt,name=invoiceNumber,proto3" json:"invoiceNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Invoice) Reset()         { *m = Invoice{} }
func (m *Invoice) String() string { return proto.CompactTextString(m) }
func (*Invoice) ProtoMessage()    {}
func (*Invoice) Descriptor() ([]byte, []int) {
	return fileDescriptor_3fdeaaf4398d3d51, []int{0}
}

func (m *Invoice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Invoice.Unmarshal(m, b)
}
func (m *Invoice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Invoice.Marshal(b, m, deterministic)
}
func (m *Invoice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Invoice.Merge(m, src)
}
func (m *Invoice) XXX_Size() int {
	return xxx_messageInfo_Invoice.Size(m)
}
func (m *Invoice) XXX_DiscardUnknown() {
	xxx_messageInfo_Invoice.DiscardUnknown(m)
}

var xxx_messageInfo_Invoice proto.InternalMessageInfo

func (m *Invoice) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Invoice) GetCustomerID() int64 {
	if m != nil {
		return m.CustomerID
	}
	return 0
}

func (m *Invoice) GetOrganizationID() int64 {
	if m != nil {
		return m.OrganizationID
	}
	return 0
}

func (m *Invoice) GetInvoiceDate() *timestamp.Timestamp {
	if m != nil {
		return m.InvoiceDate
	}
	return nil
}

func (m *Invoice) GetInvoiceNumber() string {
	if m != nil {
		return m.InvoiceNumber
	}
	return ""
}

type CreateInvoiceRequest struct {
	Invoice              *Invoice `protobuf:"bytes,1,opt,name=invoice,proto3" json:"invoice,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateInvoiceRequest) Reset()         { *m = CreateInvoiceRequest{} }
func (m *CreateInvoiceRequest) String() string { return proto.CompactTextString(m) }
func (*CreateInvoiceRequest) ProtoMessage()    {}
func (*CreateInvoiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3fdeaaf4398d3d51, []int{1}
}

func (m *CreateInvoiceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateInvoiceRequest.Unmarshal(m, b)
}
func (m *CreateInvoiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateInvoiceRequest.Marshal(b, m, deterministic)
}
func (m *CreateInvoiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateInvoiceRequest.Merge(m, src)
}
func (m *CreateInvoiceRequest) XXX_Size() int {
	return xxx_messageInfo_CreateInvoiceRequest.Size(m)
}
func (m *CreateInvoiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateInvoiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateInvoiceRequest proto.InternalMessageInfo

func (m *CreateInvoiceRequest) GetInvoice() *Invoice {
	if m != nil {
		return m.Invoice
	}
	return nil
}

type CreateInvoiceResponse struct {
	Invoice              *Invoice `protobuf:"bytes,1,opt,name=invoice,proto3" json:"invoice,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateInvoiceResponse) Reset()         { *m = CreateInvoiceResponse{} }
func (m *CreateInvoiceResponse) String() string { return proto.CompactTextString(m) }
func (*CreateInvoiceResponse) ProtoMessage()    {}
func (*CreateInvoiceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3fdeaaf4398d3d51, []int{2}
}

func (m *CreateInvoiceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateInvoiceResponse.Unmarshal(m, b)
}
func (m *CreateInvoiceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateInvoiceResponse.Marshal(b, m, deterministic)
}
func (m *CreateInvoiceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateInvoiceResponse.Merge(m, src)
}
func (m *CreateInvoiceResponse) XXX_Size() int {
	return xxx_messageInfo_CreateInvoiceResponse.Size(m)
}
func (m *CreateInvoiceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateInvoiceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateInvoiceResponse proto.InternalMessageInfo

func (m *CreateInvoiceResponse) GetInvoice() *Invoice {
	if m != nil {
		return m.Invoice
	}
	return nil
}

func init() {
	proto.RegisterType((*Invoice)(nil), "ps.Invoice")
	proto.RegisterType((*CreateInvoiceRequest)(nil), "ps.CreateInvoiceRequest")
	proto.RegisterType((*CreateInvoiceResponse)(nil), "ps.CreateInvoiceResponse")
}

func init() {
	proto.RegisterFile("ps/ps.proto", fileDescriptor_3fdeaaf4398d3d51)
}

var fileDescriptor_3fdeaaf4398d3d51 = []byte{
	// 335 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0xc6, 0x6d, 0xa7, 0x0e, 0x53, 0xb6, 0x43, 0x98, 0x50, 0x2b, 0xe8, 0x28, 0x2a, 0x03, 0x31,
	0x85, 0x79, 0x55, 0x0f, 0x6e, 0x08, 0xbb, 0x88, 0x54, 0x0f, 0xe2, 0x2d, 0xed, 0x9e, 0xdd, 0x63,
	0xa6, 0x89, 0x49, 0x3a, 0xd8, 0xfe, 0x3f, 0xff, 0x2f, 0x59, 0xbb, 0xe2, 0x36, 0x76, 0xf0, 0x98,
	0xef, 0xfb, 0x7d, 0x79, 0xdf, 0x7b, 0xc4, 0x53, 0x26, 0x52, 0x86, 0x29, 0x2d, 0xad, 0xa4, 0xae,
	0x32, 0xc1, 0x69, 0x26, 0x65, 0xf6, 0x05, 0x51, 0xa9, 0x24, 0xc5, 0x67, 0x04, 0x42, 0xd9, 0x79,
	0x05, 0x04, 0xe7, 0xdb, 0xa6, 0x45, 0x01, 0xc6, 0x72, 0xa1, 0x2a, 0x20, 0xfc, 0x71, 0x48, 0x73,
	0x94, 0xcf, 0x24, 0xa6, 0x40, 0xdb, 0xc4, 0xc5, 0xb1, 0xef, 0x74, 0x9d, 0x5e, 0x23, 0x76, 0x71,
	0x4c, 0xcf, 0x08, 0x49, 0x0b, 0x63, 0xa5, 0x00, 0x3d, 0x1a, 0xfa, 0x6e, 0xa9, 0xaf, 0x29, 0xf4,
	0x8a, 0xb4, 0xa5, 0xce, 0x78, 0x8e, 0x0b, 0x6e, 0x51, 0xe6, 0xa3, 0xa1, 0xdf, 0x28, 0x99, 0x2d,
	0x95, 0xde, 0x11, 0x0f, 0xab, 0x11, 0x43, 0x6e, 0xc1, 0xdf, 0xef, 0x3a, 0x3d, 0xaf, 0x1f, 0xb0,
	0xaa, 0x1a, 0xab, 0xab, 0xb1, 0xb7, 0xba, 0x5a, 0xbc, 0x8e, 0xd3, 0x0b, 0xd2, 0x5a, 0x3d, 0x9f,
	0x0b, 0x91, 0x80, 0xf6, 0x0f, 0xba, 0x4e, 0xef, 0x28, 0xde, 0x14, 0xc3, 0x7b, 0xd2, 0x19, 0x68,
	0xe0, 0x16, 0x56, 0xcb, 0xc4, 0xf0, 0x5d, 0x80, 0xb1, 0xf4, 0x92, 0x34, 0x57, 0x60, 0xb9, 0x98,
	0xd7, 0xf7, 0x98, 0x32, 0xac, 0x86, 0x6a, 0x2f, 0x7c, 0x20, 0xc7, 0x5b, 0x71, 0xa3, 0x64, 0x6e,
	0xe0, 0x9f, 0xf9, 0xfe, 0x3b, 0x69, 0xbf, 0xf0, 0xb9, 0x80, 0xdc, 0xbe, 0x82, 0x9e, 0x2d, 0x8f,
	0xf9, 0x44, 0x5a, 0x1b, 0x3f, 0x52, 0x7f, 0x19, 0xdc, 0xd5, 0x31, 0x38, 0xd9, 0xe1, 0x54, 0xe3,
	0xc3, 0xbd, 0xc7, 0x01, 0xe9, 0xa0, 0x64, 0xe9, 0x04, 0xb5, 0x32, 0x96, 0xa7, 0x53, 0xc6, 0x15,
	0x32, 0x65, 0x3e, 0xae, 0x33, 0xb4, 0x93, 0x22, 0x61, 0xa9, 0x14, 0x11, 0x26, 0x9a, 0x4f, 0x50,
	0xc8, 0x05, 0x4c, 0x31, 0xc5, 0xe8, 0x0f, 0xbe, 0xe1, 0x0a, 0x23, 0x65, 0x92, 0xc3, 0xf2, 0xc8,
	0xb7, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x07, 0x50, 0x42, 0x05, 0x3d, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PaymentServiceClient is the client API for PaymentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PaymentServiceClient interface {
	CreateInvoice(ctx context.Context, in *CreateInvoiceRequest, opts ...grpc.CallOption) (*CreateInvoiceResponse, error)
}

type paymentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentServiceClient(cc grpc.ClientConnInterface) PaymentServiceClient {
	return &paymentServiceClient{cc}
}

func (c *paymentServiceClient) CreateInvoice(ctx context.Context, in *CreateInvoiceRequest, opts ...grpc.CallOption) (*CreateInvoiceResponse, error) {
	out := new(CreateInvoiceResponse)
	err := c.cc.Invoke(ctx, "/ps.PaymentService/CreateInvoice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentServiceServer is the server API for PaymentService service.
type PaymentServiceServer interface {
	CreateInvoice(context.Context, *CreateInvoiceRequest) (*CreateInvoiceResponse, error)
}

// UnimplementedPaymentServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPaymentServiceServer struct {
}

func (*UnimplementedPaymentServiceServer) CreateInvoice(ctx context.Context, req *CreateInvoiceRequest) (*CreateInvoiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateInvoice not implemented")
}

func RegisterPaymentServiceServer(s *grpc.Server, srv PaymentServiceServer) {
	s.RegisterService(&_PaymentService_serviceDesc, srv)
}

func _PaymentService_CreateInvoice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateInvoiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).CreateInvoice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ps.PaymentService/CreateInvoice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).CreateInvoice(ctx, req.(*CreateInvoiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PaymentService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ps.PaymentService",
	HandlerType: (*PaymentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateInvoice",
			Handler:    _PaymentService_CreateInvoice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ps/ps.proto",
}
